### ISSUE TITLE
Tag new release of wasmtime-provider

### ISSUE THREAD

**Issue by flavio** [wapc/wapc-rs#17]
The version of wasmtime-provider has been bumped inside of its `Cargo.toml` file, but the git tag and the crates.io release are missing.

Could you please take care of that? :pray: 

@jsoverson @pkedy

**Comment by jsoverson** [comment]
Published https://crates.io/crates/wasmtime-provider/1.3.0 @flavio

**Comment by flavio** [comment]
thanks a lot @jsoverson !!!
